unicef/publicgoods-toolkit

README.md
=> Added "About the Toolkit" Section

LICENSE, README.md
=> DOC: add LICENSE

resources.md
This report is useful to anybody trying to understand the state of FOSS in India, but it also has some strategy recommendations that are of general interest.
=> Add state of foss in india report to resources

readiness.md
=> First draft of Readiness module

interview-questions.md
A default list of interview questions to ask.  We will usually cover all this in the course of an interview, but this isn't a survey.  We do not plan to ask each of these questions in these precise ways.  In most interviews, we start out asking general questions and then deep dive as interesting topics arise.  Time constraints prevent covering everything we would like.  Still, we'll get what we need.
=> Add interview questions

introduction.md
First draft of introduction, ready for review.
=> First draft of Introduction

procurement.md
=> First draft of procurement module

introduction.md, procurement.md, readiness.md
This addresses a comment first made (in PR #13) about the Introduction,
but addresses it in each of the modules, not only in the Introduction.
=> Expand "FOSS" acronym on first use in each module

introduction.md
This PR addresses the points raised by the review of PR 13.  It is all typos and minor language adjustments.  The most significant language change is substituting "protective" for "restrictive" in describing less permissive licenses.
=> Address PR 13 points

community.md
This is a rewrite of the first draft of community.md.  Most paragraphs got at least a little touch up.  The goal here was to go one level deeper.  I left the TBDs unresolved, pending info from the interviews.
=> Second version of community and ecosystem

adoptability.md, appendix-examples.md
Add appendix of examples for the toolkit.  We'll continue to add as we go, but this is a good start and can be merged as a standalone file.
=> Appendix examples

adoptability.md
This is all trivial typo fixes, except for one place where I converted a parenthetical aside into a new paragraph and reworded it, to make its point more clearly and emphatically.
=> Fix a bunch of typos and reword one passage

adoptability.md
* Add a key recommendation on ecosystem mapping
* Note support variance over time
=> Adoptability

.gitignore, adoptability.md, policy.md
This branch is for all the tiny tweaks I'm making as I go through the document tying examples to key recommendations.  This branch is *not* for connecting examples and recommendations -- that will be a separate branch/PR (or maybe several of them).  This branch is just a place to put all the other typo fixes, formatting fixes, etc, that we make along the way, so that we can keep those isolated from the more substantive changes.
Not ready for review yet.  I'll remove this line when the PR is ready for review.
=> Various small, non-substantive fixes.

appendix-examples.md, appendix-resources-tools.md, appendix-sample-contract.md, policy.md, works-consulted.md
Cleaned up Appendices. Some changes to Policy and Works Consulted, which is still WIP.
=> Appendix cleanup

adoptability.md, appendix-sample-contract.md, community.md, introduction.md, policy.md, procurement.md, readiness.md
Better clarified the audience for the toolkit, especially around policy, and included a few notations of "FUTURE WORK" to suggest where new development might be merited.
=> Edits to clarify the audience and call out areas for future work

appendix-sample-contract.md, appendix-works-consulted.md
Fixes ordering of some text in the appendix to make it clear that only the data protection and security language is from Eckert Seamans. This was per their request.
=> Fix ordering of appendix sample contract

.github/workflows/release.yml, docs/adoptability.md
(As discussed in review for already-merged PR #71.)
=> A few very minor wording tweaks in adoptability.md

docs/adoptability.md, docs/appendix-examples.md, docs/appendix-resources-tools.md, docs/appendix-sample-contract.md, docs/introduction.md, docs/policy.md, docs/readiness.md
This PR should be merged *after* PR #72.
=> Formatting fixes

docs/appendix-resources-tools.md
Thanks to David Myers for the bug report.
=> Fix link by fixing Markdown format error
